{
 "title": "Locations",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "greenacres, enfield, enfield-lab, mawsonlakes, mawsonlakes-lab"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"location\"] == \"${location}\") \n |> filter(fn: (r) => r[\"_field\"] == \"temperature_10\")\n |> set(key: \"_field\", value: \"Temperature\")\n |> drop(columns: [\"_measurement\", \"location\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Concentration CO2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"location\"] == \"${location}\") \n |> filter(fn: (r) => r[\"_field\"] == \"power_10\")\n |> set(key: \"_field\", value: \"CO2 PPM\")\n |> drop(columns: [\"_measurement\", \"location\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"location\"] == \"${location}\") \n |> filter(fn: (r) => r[\"_field\"] == \"relative_humidity_10\")\n |> set(key: \"_field\", value: \"Relative Humidity\") \n |> drop(columns: [\"_measurement\", \"location\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"location\"] == \"${location}\") \n |> filter(fn: (r) => r[\"_field\"] == \"voltage_0\")\n  |> set(key: \"_field\", value: \"Solar\")\n |> drop(columns: [\"_measurement\", \"name\", \"location\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"location\"] == \"${location}\") \n |> filter(fn: (r) => r[\"_field\"] == \"voltage_1\")\n |> set(key: \"_field\", value: \"Battery\")\n |> drop(columns: [\"_measurement\", \"name\", \"location\",\"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}