{
 "title": "Sensors",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor",
    "query": "mc-1,mc-2,mc-3,mc-4,mc-5,mc-6,mc-7,mc-8,mc-9,sensor-one-1,sensor-one-2,sensor-one-3,sensor-one-4,sally,jane"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 }, "options": { "content": "DHT Sensor" } },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 }, "options": { "content": "SCD30 Sensor" } },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 }, "options": { "content": "Power Monitoring" } },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 15, "y": 0 }, "options": { "content": "CCS811 Sensor" } },
  {
   "title": "Temperature [0]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"temperature_0\")\n |> drop(columns: [\"_measurement\", \"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature [10]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"temperature_10\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Power [0]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"voltage_0\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Concentration CO2 [16]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"power_16\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Relative Humidity [0]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"relative_humidity_0\")\n |> drop(columns: [\"_measurement\", \"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Relative Humidity [10]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"relative_humidity_10\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery [1]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"voltage_1\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Concentration TVOC [17]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"power_17\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature [1]",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"temperature_1\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Concentration CO2 [10]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"power_10\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Relative Humidity [1]",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"dev_id\"] == \"${sensor}\") \n |> filter(fn: (r) => r[\"_field\"] == \"relative_humidity_1\")\n |> drop(columns: [\"dev_id\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}