{
 "title": "Sensors - All",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"dev_id\",\n    predicate: (r) => true\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "repeat": "sensor",
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"_field\"] == \"temperature_10\")\n |> filter(fn: (r) => contains(value: r[\"dev_id\"], set: ${device:json}))\n |> drop(columns: [\"location\", \"_field\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"_field\"] == \"relative_humidity_10\")\n |> filter(fn: (r) => contains(value: r[\"dev_id\"], set: ${device:json}))\n |> map(fn: (r) => ({ r with _value: r._value + 0.0}))\n |> drop(columns: [\"location\", \"_field\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Concentration CO2 (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"_field\"] == \"power_10\")\n |> filter(fn: (r) => contains(value: r[\"dev_id\"], set: ${device:json}))\n |> map(fn: (r) => ({ r with _value: r._value + 0.0}))\n |> drop(columns: [\"_field\", \"location\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Solar Power (V)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"_field\"] == \"voltage_0\")\n |> filter(fn: (r) => contains(value: r[\"dev_id\"], set: ${device:json}))\n |> map(fn: (r) => ({ r with _value: r._value + 0.0}))\n |> drop(columns: [\"_field\", \"location\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"_field\"] == \"temperature_10\")\n |> filter(fn: (r) => contains(value: r[\"dev_id\"], set: ${device:json}))\n |> map(fn: (r) => ({ r with _value: r._value + 0.0}))\n |> drop(columns: [\"location\", \"_field\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"_field\"] == \"relative_humidity_10\")\n |> filter(fn: (r) => contains(value: r[\"dev_id\"], set: ${device:json}))\n |> map(fn: (r) => ({ r with _value: r._value + 0.0}))\n |> drop(columns: [\"location\", \"_field\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Concentration CO2 (ppm)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"_field\"] == \"power_10\")\n |> filter(fn: (r) => contains(value: r[\"dev_id\"], set: ${device:json}))\n |> map(fn: (r) => ({ r with _value: r._value + 0.0}))\n |> drop(columns: [\"_field\", \"location\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery (V)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"paeiot-bucket\")\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n |> filter(fn: (r) => r[\"_field\"] == \"voltage_1\")\n |> filter(fn: (r) => contains(value: r[\"dev_id\"], set: ${device:json}))\n |> map(fn: (r) => ({ r with _value: r._value + 0.0}))\n |> drop(columns: [\"_field\", \"location\", \"latitude\", \"longitude\"])\n |> aggregateWindow(every: v.windowPeriod, fn: mean)\n |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}