[[../../README.org][Top]]
-----
* Things to do (with..)                                                 :TOC_3:
  - [[#introduction][Introduction]]
  - [[#hardware][Hardware]]
    - [[#arduino][Arduino]]
    - [[#raspberry-pi][Raspberry Pi]]
    - [[#soldering-and-electronics][Soldering and Electronics]]
    - [[#circuit-boards][Circuit Boards]]
  - [[#software][Software]]
    - [[#kicad][KiCAD]]
    - [[#fritzing][Fritzing]]
  - [[#online-services][Online Services]]
    - [[#the-things-network][The Things Network]]

** Introduction 
The following are some suggestions for various IoT related activities which can
be done with hardware, software or online.

These activities can be thought of as mini-tutorials and how-to's.

(This document is a 'Work in Progress'. Suggestions for additions welcome.)

** Hardware
*** Arduino
- Sign up for an [[https://store.arduino.cc/digital/create][Arduino Cloud]] account

  This will enable you to use the Web Editor to create and load programs
  (sketches) for Arduino devices from within your computers browser.

- Download, Compile and Install an Arduino Sketch onto an Arduino Board

  The Arduino [[https://www.arduino.cc/en/Tutorial/BuiltInExamples/Blink][Blink Sketch]] is available under the available examples and will
  make the onboard LED blink.

- Modify the Blink Sketch to blink an external LED

  Details are in the Blink Sketch mentioned above.  

- Get an Arduino MKR WAN 1310 board to communicate via the LoRaWAN network

  This requires an account for "The Things Stack"..

  In the Arduino IDE, install the MKRWAN library. Open the FirstConfiguration
  sketch. Modify the sketch for the AU915 band plan, compile and install it.
  Get authorisation details from [[https://www.thethingsnetwork.org/][The Things Network]].

*** Raspberry Pi
- Download and Install RaspberryPiOS onto an SD Card

  Visit the [[https://www.raspberrypi.org/software/][RaspberryPiOS]] website, and download Raspberry Pi Imager. Other
  options include downloading an image [[raspberrypi.org/software/operating-systems][directly]] and using software like [[https://www.balena.io/etcher/][Balena
  Etcher]] to write it to an SD Card.

  There are several other image options available, including Ubuntu, LibreElec,
  and RetroPi.

- Install NodeRED 

- Connect NodeRED to The Things Network via MQTT

- Play a sound/music on the Raspberry Pi

*** Soldering and Electronics
- Build a LED flashing circuit.

- Build a LED and Button Shield for Arduino.

- Build an audio amplifier and attach to Raspberry Pi (2.5mm plug).

- Buy and assemble an electronics kit.

*** Circuit Boards
- Design a circuit board and get it manufactured. Solder it's components and
  test.

** Software
*** KiCAD

- Install [[https://www.kicad.org/][KiCAD]] 
- Extract mechanical details of the MKR-WAN-1310 (Work in progress)

  The technical design specifications of the MKR-WAN-1310 board have been made
  available via Eagle design files. Use [[https://www.kicad.org/][KiCAD]] to obtain the details for
  mechanically mounting the board.

*** Fritzing

- Install fritzing.
- Import the MKR-WAN-1310 model (Work in progress)

** Online Services
*** The Things Network
- Register with [[https://id.thethingsnetwork.org/]["The Things ID"]] system to create an account

  This is required for using [[https://www.thethingsnetwork.org/][The Things Network]]

- Create a application with The Things Network

- Register a LoRaWAN device

